### ISSUE TITLE
报错、跑不起来，盼回复下--谢谢

### ISSUE THREAD

**Issue by huimiao638** [BUGyyc/colyseus-examples#1]
Microsoft Windows [Version 10.0.18363.752]
(c) 2019 Microsoft Corporation. All rights reserved.

E:\cocos-creator\colyseus-examples>nmp install
'nmp' is not recognized as an internal or external command,
operable program or batch file.

E:\cocos-creator\colyseus-examples>npm install
Terminate batch job (Y/N)?
^C
E:\cocos-creator\colyseus-examples>

E:\cocos-creator\colyseus-examples>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN colyseus-examples@1.0.0 No repository field.

added 280 packages from 329 contributors and audited 1297 packages in 29.279s
found 0 vulnerabilities

E:\cocos-creator\colyseus-examples>npm start

> colyseus-examples@1.0.0 start E:\cocos-creator\colyseus-examples
> ts-node index.ts

E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:47:30 - error TS2559: Type 'Server' has no properties in common with type 'Partial<MonitorOptions>'.

47 app.use('/colyseus', monitor(gameServer));
                                ~~~~~~~~~~

    at createTSError (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:421:12)
    at reportTSError (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:425:19)
    at getOutput (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:553:36)
    at Object.compile (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:758:32)
    at Module.m._compile (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:837:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (E:\cocos-creator\colyseus-examples\node_modules\ts-node\src\index.ts:840:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! colyseus-examples@1.0.0 start: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the colyseus-examples@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\freeyun\AppData\Roaming\npm-cache\_logs\2020-03-29T03_41_17_255Z-debug.log

E:\cocos-creator\colyseus-examples>

**Comment by huimiao638** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle colyseus-examples@1.0.0~prestart: colyseus-examples@1.0.0
6 info lifecycle colyseus-examples@1.0.0~start: colyseus-examples@1.0.0
7 verbose lifecycle colyseus-examples@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle colyseus-examples@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\cocos-creator\colyseus-examples-master\node_modules\.bin;D:\Program Files (x86)\NetSarang\Xshell 6\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\Python27;D:\Android\android-sdk\platform-tools;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\CMake\bin;F:\mysql-5.7.27-winx64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\msys\1.0\bin;D:\nsq-1.1.0.windows-amd64.go1.10.3\bin;%ERLANG_HOME%\bin;C:\Program Files\dotnet\;C:\OpenSSL-Win64\bin;C:\Program Files\nodejs\;C:\TDM-GCC-64\bin;D:\lua-5.3.5_Win64_bin;D:\Android\android-ndk-r12b;C:\Go\bin;C:\Program Files\TortoiseGit\bin;d:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;E:\SDK\cocos2d-x-3.16\templates;E:\SDK\cocos2d-x-3.16\tools\cocos2d-console\bin;E:\SDK;C:\Users\freeyun\AppData\Local\Microsoft\WindowsApps;C:\Programs\Microsoft VS Code\bin;C:\Users\freeyun\AppData\Roaming\npm;D:\gopath\bin;C:\Users\freeyun\go\bin
9 verbose lifecycle colyseus-examples@1.0.0~start: CWD: E:\cocos-creator\colyseus-examples-master
10 silly lifecycle colyseus-examples@1.0.0~start: Args: [ '/d /s /c', 'ts-node index.ts' ]
11 silly lifecycle colyseus-examples@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle colyseus-examples@1.0.0~start: Failed to exec start script
13 verbose stack Error: colyseus-examples@1.0.0 start: `ts-node index.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid colyseus-examples@1.0.0
15 verbose cwd E:\cocos-creator\colyseus-examples-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error colyseus-examples@1.0.0 start: `ts-node index.ts`
22 error Exit status 1
23 error Failed at the colyseus-examples@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
